import login
from PyQt5 import QtCore, QtGui, QtWidgets
players={}
from data import outy,outb,outg,outr



class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1180, 838)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 212, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 212, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 113, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Form.setPalette(palette)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(600, 130, 501, 511))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("./newboard.jpg"))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(60, 110, 211, 261))
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 40, 151, 181))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(-3, 480, 411, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(400, -10, 20, 871))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(60, 550, 256, 192))
        self.listWidget.setObjectName("listWidget")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(710, 680, 311, 119))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar_1 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_1.setProperty("value", 0)
        self.progressBar_1.setStyleSheet("QProgressBar::chunk ""{""background-color: greenyellow;""}")
        self.progressBar_1.setObjectName("progressBar_1")
        self.gridLayout.addWidget(self.progressBar_1, 0, 1, 1, 1)
        self.progressBar_5 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_5.setProperty("value", 0)
        self.progressBar_5.setStyleSheet("QProgressBar::chunk ""{""background-color: greenyellow;""}")
        self.progressBar_5.setObjectName("progressBar_5")
        self.gridLayout.addWidget(self.progressBar_5, 3, 1, 1, 1)
        self.progressBar_4 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_4.setProperty("value", 0)
        self.progressBar_4.setStyleSheet("QProgressBar::chunk ""{""background-color: greenyellow;""}")
        self.progressBar_4.setObjectName("progressBar_4")
        self.gridLayout.addWidget(self.progressBar_4, 2, 1, 1, 1)
        self.progressBar_3 = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setStyleSheet("QProgressBar::chunk ""{""background-color: greenyellow;""}")
        self.progressBar_3.setObjectName("progressBar_3")
        self.gridLayout.addWidget(self.progressBar_3, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(730, 40, 168, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Turn = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_Turn.setObjectName("label_Turn")
        self.verticalLayout.addWidget(self.label_Turn)
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalLayoutWidget)
        self.lcdNumber.setObjectName("lcdNumber")
        self.horizontalLayout.addWidget(self.lcdNumber)
        self.label_Players = QtWidgets.QLabel(Form)
        self.label_Players.setGeometry(QtCore.QRect(60, 510, 81, 31))
        self.label_Players.setObjectName("label_Players")
        self.mohre1 = QtWidgets.QPushButton(Form)
        self.mohre1.setObjectName("mohre1")
        self.mohre3 = QtWidgets.QPushButton(Form)
        self.mohre3.setObjectName("mohre3")
        self.mohre11 = QtWidgets.QPushButton(Form)
        self.mohre11.setObjectName("mohre11")
        self.mohre2 = QtWidgets.QPushButton(Form)
        self.mohre2.setObjectName("mohre2")
        self.mohre9 = QtWidgets.QPushButton(Form)
        self.mohre9.setObjectName("mohre9")
        self.mohre10 = QtWidgets.QPushButton(Form)
        self.mohre10.setObjectName("mohre10")
        self.mohre8 = QtWidgets.QPushButton(Form)
        self.mohre8.setObjectName("mohre8")
        self.mohre7 = QtWidgets.QPushButton(Form)
        self.mohre7.setObjectName("mohre7")
        self.mohre6 = QtWidgets.QPushButton(Form)
        self.mohre6.setObjectName("mohre6")
        self.mohre5 = QtWidgets.QPushButton(Form)
        self.mohre5.setObjectName("mohre5")
        self.mohre4 = QtWidgets.QPushButton(Form)
        self.mohre4.setObjectName("mohre4")
        self.mohre12 = QtWidgets.QPushButton(Form)
        self.mohre12.setObjectName("mohre12")
        self.mohre13 = QtWidgets.QPushButton(Form)
        self.mohre13.setObjectName("mohre13")
        self.mohre14= QtWidgets.QPushButton(Form)
        self.mohre14.setObjectName("mohre14")
        self.mohre15 = QtWidgets.QPushButton(Form)
        self.mohre15.setObjectName("mohre15")
        self.mohre16 = QtWidgets.QPushButton(Form)
        self.mohre16.setObjectName("mohre16")
        self.yellow=[self.mohre1,self.mohre2,self.mohre3,self.mohre4]
        for i in range(4):
            self.yellow[i].setGeometry(QtCore.QRect(outy[i][0],outy[i][1], 30, 40))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("colors/yellow.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.yellow[i].setIcon(icon)
            self.yellow[i].setIconSize(QtCore.QSize(30, 40))
        self.blue = [self.mohre5, self.mohre6, self.mohre7, self.mohre8]
        for i in range(4):
            self.blue[i].setGeometry(QtCore.QRect(outb[i][0], outb[i][1], 30, 40))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("colors/blue.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.blue[i].setIcon(icon)
            self.blue[i].setIconSize(QtCore.QSize(30, 40))
        self.green = [self.mohre9, self.mohre10, self.mohre11, self.mohre12]
        for i in range(4):
            self.green[i].setGeometry(QtCore.QRect(outg[i][0], outg[i][1], 30, 40))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("colors/green.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.green[i].setIcon(icon)
            self.green[i].setIconSize(QtCore.QSize(30, 40))
        self.red = [self.mohre13, self.mohre14, self.mohre15, self.mohre16]
        for i in range(4):
            self.red[i].setGeometry(QtCore.QRect(outr[i][0], outr[i][1], 30, 40))
            icon = QtGui.QIcon()
            icon.addPixmap(QtGui.QPixmap("colors/red.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.red[i].setIcon(icon)
            self.red[i].setIconSize(QtCore.QSize(30, 40))
        for i in [self.yellow,self.blue,self.green,self.red]:
            for j in i:
                j.setEnabled(False)



        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Game"))
        self.pushButton.setText(_translate("Form", "Add Player"))
        self.pushButton_4.setText(_translate("Form", "Start Game"))
        self.pushButton_3.setText(_translate("Form", "New game"))
        self.pushButton_2.setText(_translate("Form", "Exit"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.label_2.setText(_translate("Form", "player1"))
        self.label_3.setText(_translate("Form", "player2"))
        self.label_4.setText(_translate("Form", "player3"))
        self.label_5.setText(_translate("Form", "player4"))
        self.label_Turn.setText(_translate("Form", "Turn:"))
        self.pushButton_5.setText(_translate("Form", "Roll"))
        self.label_Players.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Players:</span></p></body></html>"))
        # self.mohre1.setText(_translate("Form", "PushButton"))
        # self.mohre3.setText(_translate("Form", "PushButton"))
        # self.mohre11.setText(_translate("Form", "PushButton"))
        # self.mohre2.setText(_translate("Form", "PushButton"))
        # self.mohre9.setText(_translate("Form", "PushButton"))
        # self.mohre10.setText(_translate("Form", "PushButton"))
        # self.mohre8.setText(_translate("Form", "PushButton"))
        # self.mohre7.setText(_translate("Form", "PushButton"))
        # self.mohre6.setText(_translate("Form", "PushButton"))
        # self.mohre5.setText(_translate("Form", "PushButton"))
        # self.mohre4.setText(_translate("Form", "PushButton"))
        # self.mohre12.setText(_translate("Form", "PushButton"))


    def add_list(self,user,index):
        self.listWidget.addItem("player" + str(index) +" : " +user)





    def add_player(self,l0):
        res=l0.check()
        if res[0]:
            user=res[1]
            color=res[2]
            players[user]=color
            l0.comboBox.removeItem(res[3])
            login.userpass.pop(user)
            self.add_list(user,len(players))
            d.close()
            l0.lineEdit.clear()
            l0.lineEdit_2.clear()




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    ##_______________________________________________
    l=login.Ui_LoginForm()
    d=QtWidgets.QDialog()
    l.setupUi(d)
    ui.pushButton.clicked.connect(lambda : d.exec_())
    l.pushButton.clicked.connect(lambda : ui.add_player(l))
    ##_______________________________________________
    sys.exit(app.exec_())
